### ISSUE TITLE
Parent problem

### ISSUE THREAD

**Issue by phoe** [sjl/rosalind#1]
https://github.com/sjl/rosalind/blob/ef6194d94c8fe85b53fd0a7811f7ba85c4809bb0/rosalind.asd#L7

Won't a parent of `self` result in a grandparent of the file? Shouldn't this be just `self`?

**Comment by sjl** [comment]
I'm not sure.  I think jackdaniel originally wrote this in IRC and I've just copypasted in in all my various problem-set-repos.  They might be able to explain what they were intending, but I'm not sure myself.

Testing it really quickly locally shows it seems to work either way, so maybe ASDF doesn't care all that much whether the nodes end up as descendants of this single node or whether they get spliced into the tree where the auto module is.
